# Generated by Django 3.2.6 on 2021-10-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=700)),
                ('url', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=400)),
                ('datetime', models.DateTimeField()),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
