# Generated by Django 3.2.6 on 2021-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrate', '0002_auto_20211012_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
